### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by zQueal** [coryknapp/vim-color-flash#2]
Posted to let you know that it seems to work just fine on Windows. The only issue is, the window pops up for a few seconds and then disappears. Not very helpful in the long run -- especially so if I need to compare it to other colors. Something nice would be;

```
let g:vim_color_flash_timeout = 30
```

Adding a 30 second timeout before the window automatically closes. Or;

```
let g:vim_color_flash_timeout = 0
```

To disable automatically closing the window.

**Comment by coryknapp** [comment]
Thanks for the info about Windows.  I went ahead and added the `g:vim_color_flash_timeout` setting like you suggested, so thanks for that too.
